product: "MOD09A1.061"

start_date: "2009-12-20"
end_date: "2010-02-10"

tiles: ["h09v09","h10v11","h11v11","h12v11", "h14v09",
        "h10v07","h11v07","h12v07","h13v08", "h14v10",
        "h10v08","h11v08","h12v08","h13v09", "h14v11",
        "h10v09","h11v09","h12v09","h13v10", "h13v12",
        "h10v10","h11v10","h12v10","h13v11"]
